package net.mcreator.apocalypsenow.init;

import net.mcreator.apocalypsenow.block.AcaciaPlanksStashBlock;
import net.mcreator.apocalypsenow.block.AcaciacrateBlock;
import net.mcreator.apocalypsenow.block.AcacialogspikeBlock;
import net.mcreator.apocalypsenow.block.ApartmentdoorBlock;
import net.mcreator.apocalypsenow.block.BarbewireBlock;
import net.mcreator.apocalypsenow.block.BeartrapBlock;
import net.mcreator.apocalypsenow.block.BeartrapactivatedBlock;
import net.mcreator.apocalypsenow.block.BeartrapneutralBlock;
import net.mcreator.apocalypsenow.block.BirchPlanksStashBlock;
import net.mcreator.apocalypsenow.block.BirchcrateBlock;
import net.mcreator.apocalypsenow.block.BirchlogspikeBlock;
import net.mcreator.apocalypsenow.block.BlackConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.BlackpetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.BlueConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.BluepetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.BrokenPlasmaTvBlock;
import net.mcreator.apocalypsenow.block.BrokenTvBlock;
import net.mcreator.apocalypsenow.block.BrokenoldradioBlock;
import net.mcreator.apocalypsenow.block.BrokenpremiunradioBlock;
import net.mcreator.apocalypsenow.block.BrownConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.BrownpetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.BunkertrapdoorBlock;
import net.mcreator.apocalypsenow.block.CarboardboxBlock;
import net.mcreator.apocalypsenow.block.CherryPlanksStashBlock;
import net.mcreator.apocalypsenow.block.CherrycrateBlock;
import net.mcreator.apocalypsenow.block.CherrylogspikeBlock;
import net.mcreator.apocalypsenow.block.ClaymoreBlock;
import net.mcreator.apocalypsenow.block.ClimbingRopeBlock;
import net.mcreator.apocalypsenow.block.ClimbingropeextensionBlock;
import net.mcreator.apocalypsenow.block.ClimbingropehookBlock;
import net.mcreator.apocalypsenow.block.CokevendingmachineBlock;
import net.mcreator.apocalypsenow.block.ConcretbarrierBlock;
import net.mcreator.apocalypsenow.block.ConcretbarrierwhiteBlock;
import net.mcreator.apocalypsenow.block.ConcretbricksBlock;
import net.mcreator.apocalypsenow.block.ConstructionbarricadeBlock;
import net.mcreator.apocalypsenow.block.CorpseclothBlock;
import net.mcreator.apocalypsenow.block.CorpsesackBlock;
import net.mcreator.apocalypsenow.block.CrossBlock;
import net.mcreator.apocalypsenow.block.CyanconcretebricksBlock;
import net.mcreator.apocalypsenow.block.CyanpetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.DarkPlanksStashBlock;
import net.mcreator.apocalypsenow.block.DarkcrateBlock;
import net.mcreator.apocalypsenow.block.DarklogspikeBlock;
import net.mcreator.apocalypsenow.block.DesertmilitarystorageBlock;
import net.mcreator.apocalypsenow.block.DropboxcommonBlock;
import net.mcreator.apocalypsenow.block.ElectricDoorBlock;
import net.mcreator.apocalypsenow.block.EletricfenceBlock;
import net.mcreator.apocalypsenow.block.EletricfencesignBlock;
import net.mcreator.apocalypsenow.block.EmptymarketshelvesBlock;
import net.mcreator.apocalypsenow.block.ExplosiveBarrelBlock;
import net.mcreator.apocalypsenow.block.GascanisterBlock;
import net.mcreator.apocalypsenow.block.GlassSpikesBlock;
import net.mcreator.apocalypsenow.block.GlassdoorBlock;
import net.mcreator.apocalypsenow.block.GravestoneBlock;
import net.mcreator.apocalypsenow.block.GraypetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.GreenConcretebricksBlock;
import net.mcreator.apocalypsenow.block.GreenpetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.HighvaluemoneyblockBlock;
import net.mcreator.apocalypsenow.block.HospitalDoorBlock;
import net.mcreator.apocalypsenow.block.IceBlock;
import net.mcreator.apocalypsenow.block.IroncrateBlock;
import net.mcreator.apocalypsenow.block.IrongridBlock;
import net.mcreator.apocalypsenow.block.IrongriddoorBlock;
import net.mcreator.apocalypsenow.block.IronladderBlock;
import net.mcreator.apocalypsenow.block.IronlockerBlock;
import net.mcreator.apocalypsenow.block.IronplateBlock;
import net.mcreator.apocalypsenow.block.IronsafeBlock;
import net.mcreator.apocalypsenow.block.IronwindowBlock;
import net.mcreator.apocalypsenow.block.JunglePlanksStashBlock;
import net.mcreator.apocalypsenow.block.JunglecrateBlock;
import net.mcreator.apocalypsenow.block.JunglelogspikeBlock;
import net.mcreator.apocalypsenow.block.LandmineBlock;
import net.mcreator.apocalypsenow.block.LargegascanisterBlock;
import net.mcreator.apocalypsenow.block.LargeshelvesBlock;
import net.mcreator.apocalypsenow.block.LargeshelvesfillBlock;
import net.mcreator.apocalypsenow.block.LeavesTrapBlock;
import net.mcreator.apocalypsenow.block.LightBlueconcretebricksBlock;
import net.mcreator.apocalypsenow.block.LightGrayConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.LightbluepetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.LigthgraypetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.LimeConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.LimepetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.LogwithstoneBlock;
import net.mcreator.apocalypsenow.block.MagazineBoxesBlock;
import net.mcreator.apocalypsenow.block.MagentaconcretebricksBlock;
import net.mcreator.apocalypsenow.block.MagentapetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.MangrovePlanksStashBlock;
import net.mcreator.apocalypsenow.block.MangrovecrateBlock;
import net.mcreator.apocalypsenow.block.MangrovelogspikeBlock;
import net.mcreator.apocalypsenow.block.MarketfridgeBlock;
import net.mcreator.apocalypsenow.block.MarketshelvesBlock;
import net.mcreator.apocalypsenow.block.MechanicsToolChestBlock;
import net.mcreator.apocalypsenow.block.MedicalBoxBlock;
import net.mcreator.apocalypsenow.block.MedicalStorageBlock;
import net.mcreator.apocalypsenow.block.MedicalairdropboxBlock;
import net.mcreator.apocalypsenow.block.MedicineboxesBlock;
import net.mcreator.apocalypsenow.block.MetalShelvesBlock;
import net.mcreator.apocalypsenow.block.MetalShevelstwoBlock;
import net.mcreator.apocalypsenow.block.MetalbarsBlock;
import net.mcreator.apocalypsenow.block.MetalshelvesfiveBlock;
import net.mcreator.apocalypsenow.block.MetalshelvesoneBlock;
import net.mcreator.apocalypsenow.block.MetalshelvesthreeBlock;
import net.mcreator.apocalypsenow.block.MetelshelvesfourBlock;
import net.mcreator.apocalypsenow.block.MilitaryairdropBlock;
import net.mcreator.apocalypsenow.block.MilitaryboxBlock;
import net.mcreator.apocalypsenow.block.MilitarycommunicationradioBlock;
import net.mcreator.apocalypsenow.block.MilitarydoorBlock;
import net.mcreator.apocalypsenow.block.MilitarystorageBlock;
import net.mcreator.apocalypsenow.block.MoneyblockBlock;
import net.mcreator.apocalypsenow.block.MossbricksBlock;
import net.mcreator.apocalypsenow.block.MossbrickslabBlock;
import net.mcreator.apocalypsenow.block.MossbrickwallBlock;
import net.mcreator.apocalypsenow.block.MosstairsBlock;
import net.mcreator.apocalypsenow.block.OakPlanksStashBlock;
import net.mcreator.apocalypsenow.block.OaklogspikeBlock;
import net.mcreator.apocalypsenow.block.OrangeConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.OrangepetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.PackofcannedbeansBlock;
import net.mcreator.apocalypsenow.block.PackofcannedbeetrootBlock;
import net.mcreator.apocalypsenow.block.PackofcannedcarrotsBlock;
import net.mcreator.apocalypsenow.block.PackofcannedchilieBlock;
import net.mcreator.apocalypsenow.block.PackofcannedcornBlock;
import net.mcreator.apocalypsenow.block.PackofcanneddogsfoodBlock;
import net.mcreator.apocalypsenow.block.PackofcannedfishBlock;
import net.mcreator.apocalypsenow.block.PackofcannedfoodBlock;
import net.mcreator.apocalypsenow.block.PackofcannedmelonBlock;
import net.mcreator.apocalypsenow.block.PackofcannedporkBlock;
import net.mcreator.apocalypsenow.block.PackofcannedrabbitsoupBlock;
import net.mcreator.apocalypsenow.block.PackofcannedsoupBlock;
import net.mcreator.apocalypsenow.block.PackofcannedstawberryBlock;
import net.mcreator.apocalypsenow.block.PackofmilkboxesBlock;
import net.mcreator.apocalypsenow.block.PalletBlock;
import net.mcreator.apocalypsenow.block.PalletSlabBlock;
import net.mcreator.apocalypsenow.block.PalletStorageBlock;
import net.mcreator.apocalypsenow.block.PaperstrashBlock;
import net.mcreator.apocalypsenow.block.Paperstrashvariant2Block;
import net.mcreator.apocalypsenow.block.Papersvariant2Block;
import net.mcreator.apocalypsenow.block.PapertrashBlock;
import net.mcreator.apocalypsenow.block.PapertrashvariantBlock;
import net.mcreator.apocalypsenow.block.PetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.PileoftiresBlock;
import net.mcreator.apocalypsenow.block.PinkConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.PinkpetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.PlanedoorBlock;
import net.mcreator.apocalypsenow.block.PlankDoorBlock;
import net.mcreator.apocalypsenow.block.PlanksABlock;
import net.mcreator.apocalypsenow.block.PlanksbBlock;
import net.mcreator.apocalypsenow.block.PlankscBlock;
import net.mcreator.apocalypsenow.block.PlanksdBlock;
import net.mcreator.apocalypsenow.block.PlankseBlock;
import net.mcreator.apocalypsenow.block.PorpsivendingmachineBlock;
import net.mcreator.apocalypsenow.block.PrisondoorBlock;
import net.mcreator.apocalypsenow.block.ProtectiongridBlock;
import net.mcreator.apocalypsenow.block.PurpleConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.PurplepetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.RainCollectorBlock;
import net.mcreator.apocalypsenow.block.RainCollectorFullBlock;
import net.mcreator.apocalypsenow.block.RedconcretebricksBlock;
import net.mcreator.apocalypsenow.block.RedpetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.ReiforceddoorBlock;
import net.mcreator.apocalypsenow.block.ReiforcedwooddoorBlock;
import net.mcreator.apocalypsenow.block.RockpileBlock;
import net.mcreator.apocalypsenow.block.RopeBlock;
import net.mcreator.apocalypsenow.block.RopeextensionBlock;
import net.mcreator.apocalypsenow.block.SandbagbarrierBlock;
import net.mcreator.apocalypsenow.block.SandbagsBlock;
import net.mcreator.apocalypsenow.block.SandbagsslabBlock;
import net.mcreator.apocalypsenow.block.SandbagsstarBlock;
import net.mcreator.apocalypsenow.block.ScrapmetalblockBlock;
import net.mcreator.apocalypsenow.block.SedexboxBlock;
import net.mcreator.apocalypsenow.block.SewageHatchBlock;
import net.mcreator.apocalypsenow.block.SpikebarrierBlock;
import net.mcreator.apocalypsenow.block.SpikefenceBlock;
import net.mcreator.apocalypsenow.block.SpikefenceturnBlock;
import net.mcreator.apocalypsenow.block.SpikelogBlock;
import net.mcreator.apocalypsenow.block.SpikesBlock;
import net.mcreator.apocalypsenow.block.SpikeswallBlock;
import net.mcreator.apocalypsenow.block.SprucePlanksStashBlock;
import net.mcreator.apocalypsenow.block.SprucecrateBlock;
import net.mcreator.apocalypsenow.block.SprucelogspikeBlock;
import net.mcreator.apocalypsenow.block.TanktrapBlock;
import net.mcreator.apocalypsenow.block.ToxicwastebarrelBlock;
import net.mcreator.apocalypsenow.block.TrafficbarricadeBlock;
import net.mcreator.apocalypsenow.block.TrashbagBlock;
import net.mcreator.apocalypsenow.block.TrashbagblueplasticBlock;
import net.mcreator.apocalypsenow.block.Trashcan1Block;
import net.mcreator.apocalypsenow.block.TrashcanBlock;
import net.mcreator.apocalypsenow.block.TrashcannBlock;
import net.mcreator.apocalypsenow.block.TallBlockProxyBlock;
import net.mcreator.apocalypsenow.block.VentBlock;
import net.mcreator.apocalypsenow.block.VentblockBlock;
import net.mcreator.apocalypsenow.block.VentcoverBlock;
import net.mcreator.apocalypsenow.block.VententranceBlock;
import net.mcreator.apocalypsenow.block.VentturnBlock;
import net.mcreator.apocalypsenow.block.WashingmachineBlock;
import net.mcreator.apocalypsenow.block.WhiteConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.WhitepetrolbarrelBlock;
import net.mcreator.apocalypsenow.block.WirefenceBlock;
import net.mcreator.apocalypsenow.block.WoodencrateBlock;
import net.mcreator.apocalypsenow.block.YellowConcreteBricksBlock;
import net.mcreator.apocalypsenow.block.YellowpetrolbarrelBlock;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ApocalypsenowModBlocks {
   public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, "apocalypsenow");
   public static final RegistryObject<Block> PROTECTION_GRID = REGISTRY.register("protection_grid", () -> new ProtectiongridBlock());
   public static final RegistryObject<Block> WIRE_FENCE = REGISTRY.register("wire_fence", () -> new WirefenceBlock());
   public static final RegistryObject<Block> IRON_WINDOW = REGISTRY.register("iron_window", () -> new IronwindowBlock());
   public static final RegistryObject<Block> IRON_GRID = REGISTRY.register("iron_grid", () -> new IrongridBlock());
   public static final RegistryObject<Block> BARBED_WIRE = REGISTRY.register("barbed_wire", () -> new BarbewireBlock());
   public static final RegistryObject<Block> ELECTRIC_FENCE = REGISTRY.register("electric_fence", () -> new EletricfenceBlock());
   public static final RegistryObject<Block> SCRAP_METAL_BLOCK = REGISTRY.register("scrap_metal_block", () -> new ScrapmetalblockBlock());
   public static final RegistryObject<Block> ROPE = REGISTRY.register("rope", () -> new RopeBlock());
   public static final RegistryObject<Block> ELETRICFENCESIGN = REGISTRY.register("eletricfencesign", () -> new EletricfencesignBlock());
   public static final RegistryObject<Block> SANDBAGS = REGISTRY.register("sandbags", () -> new SandbagsBlock());
   public static final RegistryObject<Block> SANDBAGSSTAR = REGISTRY.register("sandbagsstar", () -> new SandbagsstarBlock());
   public static final RegistryObject<Block> SANDBAGSSLAB = REGISTRY.register("sandbagsslab", () -> new SandbagsslabBlock());
   public static final RegistryObject<Block> WOODEN_CRATE = REGISTRY.register("wooden_crate", () -> new WoodencrateBlock());
   public static final RegistryObject<Block> MILITARY_CRATE = REGISTRY.register("military_crate", () -> new MilitaryboxBlock());
   public static final RegistryObject<Block> MEDICAL_BOX = REGISTRY.register("medical_box", () -> new MedicalBoxBlock());
   public static final RegistryObject<Block> PETROL_BARREL = REGISTRY.register("petrol_barrel", () -> new PetrolbarrelBlock());
   public static final RegistryObject<Block> PRISON_DOOR = REGISTRY.register("prison_door", () -> new PrisondoorBlock());
   public static final RegistryObject<Block> REINFORCED_DOOR = REGISTRY.register("reinforced_door", () -> new ReiforceddoorBlock());
   public static final RegistryObject<Block> MILITARY_DOOR = REGISTRY.register("military_door", () -> new MilitarydoorBlock());
   public static final RegistryObject<Block> GLASS_DOOR = REGISTRY.register("glass_door", () -> new GlassdoorBlock());
   public static final RegistryObject<Block> BUNKER_HATCH = REGISTRY.register("bunker_hatch", () -> new BunkertrapdoorBlock());
   public static final RegistryObject<Block> SPIKESWALL = REGISTRY.register("spikeswall", () -> new SpikeswallBlock());
   public static final RegistryObject<Block> SPIKE_BARRIER = REGISTRY.register("spike_barrier", () -> new SpikebarrierBlock());
   public static final RegistryObject<Block> REINFORCED_WOODEN_DOOR = REGISTRY.register("reinforced_wooden_door", () -> new ReiforcedwooddoorBlock());
   public static final RegistryObject<Block> HOSPITAL_DOOR = REGISTRY.register("hospital_door", () -> new HospitalDoorBlock());
   public static final RegistryObject<Block> PLANE_DOOR = REGISTRY.register("plane_door", () -> new PlanedoorBlock());
   public static final RegistryObject<Block> CARDBOARD_BOX = REGISTRY.register("cardboard_box", () -> new CarboardboxBlock());
   public static final RegistryObject<Block> GLASS_SPIKES = REGISTRY.register("glass_spikes", () -> new GlassSpikesBlock());
   public static final RegistryObject<Block> TANK_TRAP = REGISTRY.register("tank_trap", () -> new TanktrapBlock());
   public static final RegistryObject<Block> CONCRETE_BARRIER = REGISTRY.register("concrete_barrier", () -> new ConcretbarrierBlock());
   public static final RegistryObject<Block> LINED_CONCRETE_BARRIER = REGISTRY.register("lined_concrete_barrier", () -> new ConcretbarrierwhiteBlock());
   public static final RegistryObject<Block> CONCRETE_BRICKS = REGISTRY.register("concrete_bricks", () -> new ConcretbricksBlock());
   public static final RegistryObject<Block> LOG_WITH_STONE = REGISTRY.register("log_with_stone", () -> new LogwithstoneBlock());
   public static final RegistryObject<Block> LAND_MINE = REGISTRY.register("land_mine", () -> new LandmineBlock());
   public static final RegistryObject<Block> TRIPWIRE_BOMB = REGISTRY.register("tripwire_bomb", () -> new ClaymoreBlock());
   public static final RegistryObject<Block> SPIKES = REGISTRY.register("spikes", () -> new SpikesBlock());
   public static final RegistryObject<Block> PLANKSB = REGISTRY.register("planksb", () -> new PlanksbBlock());
   public static final RegistryObject<Block> IRON_LADDER = REGISTRY.register("iron_ladder", () -> new IronladderBlock());
   public static final RegistryObject<Block> IRON_PLATE = REGISTRY.register("iron_plate", () -> new IronplateBlock());
   public static final RegistryObject<Block> PLANKS_A = REGISTRY.register("planks_a", () -> new PlanksABlock());
   public static final RegistryObject<Block> MOSSBRICKS = REGISTRY.register("mossbricks", () -> new MossbricksBlock());
   public static final RegistryObject<Block> MOSSTAIRS = REGISTRY.register("mosstairs", () -> new MosstairsBlock());
   public static final RegistryObject<Block> MOSSBRICKSLAB = REGISTRY.register("mossbrickslab", () -> new MossbrickslabBlock());
   public static final RegistryObject<Block> MOSSBRICKWALL = REGISTRY.register("mossbrickwall", () -> new MossbrickwallBlock());
   public static final RegistryObject<Block> TRAFFIC_BARRICADE = REGISTRY.register("traffic_barricade", () -> new TrafficbarricadeBlock());
   public static final RegistryObject<Block> CROSS = REGISTRY.register("cross", () -> new CrossBlock());
   public static final RegistryObject<Block> GRAVESTONE = REGISTRY.register("gravestone", () -> new GravestoneBlock());
   public static final RegistryObject<Block> METAL_BARS = REGISTRY.register("metal_bars", () -> new MetalbarsBlock());
   public static final RegistryObject<Block> ROCKPILE = REGISTRY.register("rockpile", () -> new RockpileBlock());
   public static final RegistryObject<Block> CONSTRUCTION_BARRICADE = REGISTRY.register("construction_barricade", () -> new ConstructionbarricadeBlock());
   public static final RegistryObject<Block> MEDICAL_STORAGE = REGISTRY.register("medical_storage", () -> new MedicalStorageBlock());
   public static final RegistryObject<Block> PLANKSC = REGISTRY.register("planksc", () -> new PlankscBlock());
   public static final RegistryObject<Block> LEAVES_TRAP = REGISTRY.register("leaves_trap", () -> new LeavesTrapBlock());
   public static final RegistryObject<Block> BEAR_TRAP = REGISTRY.register("bear_trap", () -> new BeartrapBlock());
   public static final RegistryObject<Block> BEARTRAPACTIVATED = REGISTRY.register("beartrapactivated", () -> new BeartrapactivatedBlock());
   public static final RegistryObject<Block> SPIKE_LOG = REGISTRY.register("spike_log", () -> new SpikelogBlock());
   public static final RegistryObject<Block> SPIKEFENCE = REGISTRY.register("spikefence", () -> new SpikefenceBlock());
   public static final RegistryObject<Block> IRON_LOCKER = REGISTRY.register("iron_locker", () -> new IronlockerBlock());
   public static final RegistryObject<Block> SAFE = REGISTRY.register("safe", () -> new IronsafeBlock());
   public static final RegistryObject<Block> SEDEXBOX = REGISTRY.register("sedexbox", () -> new SedexboxBlock());
   public static final RegistryObject<Block> IRON_GRID_DOOR = REGISTRY.register("iron_grid_door", () -> new IrongriddoorBlock());
   public static final RegistryObject<Block> PILE_OF_TIRES = REGISTRY.register("pile_of_tires", () -> new PileoftiresBlock());
   public static final RegistryObject<Block> ELECTRIC_DOOR = REGISTRY.register("electric_door", () -> new ElectricDoorBlock());
   public static final RegistryObject<Block> EXPLOSIVE_BARREL = REGISTRY.register("explosive_barrel", () -> new ExplosiveBarrelBlock());
   public static final RegistryObject<Block> MONEY_BLOCK = REGISTRY.register("money_block", () -> new MoneyblockBlock());
   public static final RegistryObject<Block> METAL_SHELVES = REGISTRY.register("metal_shelves", () -> new MetalShelvesBlock());
   public static final RegistryObject<Block> METAL_SHELVELS_TWO = REGISTRY.register("metal_shelvels_two", () -> new MetalShevelstwoBlock());
   public static final RegistryObject<Block> METAL_SHELVES_THREE = REGISTRY.register("metal_shelves_three", () -> new MetalshelvesthreeBlock());
   public static final RegistryObject<Block> PALLET = REGISTRY.register("pallet", () -> new PalletBlock());
   public static final RegistryObject<Block> PALLET_SLAB = REGISTRY.register("pallet_slab", () -> new PalletSlabBlock());
   public static final RegistryObject<Block> PALLET_STORAGE = REGISTRY.register("pallet_storage", () -> new PalletStorageBlock());
   public static final RegistryObject<Block> SANDBAGBARRIER = REGISTRY.register("sandbagbarrier", () -> new SandbagbarrierBlock());
   public static final RegistryObject<Block> BROKEN_TV = REGISTRY.register("broken_tv", () -> new BrokenTvBlock());
   public static final RegistryObject<Block> BROKEN_PLASMA_TV = REGISTRY.register("broken_plasma_tv", () -> new BrokenPlasmaTvBlock());
   public static final RegistryObject<Block> BROKENPREMIUNRADIO = REGISTRY.register("brokenpremiunradio", () -> new BrokenpremiunradioBlock());
   public static final RegistryObject<Block> BROKENOLDRADIO = REGISTRY.register("brokenoldradio", () -> new BrokenoldradioBlock());
   public static final RegistryObject<Block> OAK_PLANKS_STASH = REGISTRY.register("oak_planks_stash", () -> new OakPlanksStashBlock());
   public static final RegistryObject<Block> SPRUCE_PLANKS_STASH = REGISTRY.register("spruce_planks_stash", () -> new SprucePlanksStashBlock());
   public static final RegistryObject<Block> BIRCH_PLANKS_STASH = REGISTRY.register("birch_planks_stash", () -> new BirchPlanksStashBlock());
   public static final RegistryObject<Block> JUNGLE_PLANKS_STASH = REGISTRY.register("jungle_planks_stash", () -> new JunglePlanksStashBlock());
   public static final RegistryObject<Block> ACACIA_PLANKS_STASH = REGISTRY.register("acacia_planks_stash", () -> new AcaciaPlanksStashBlock());
   public static final RegistryObject<Block> DARK_PLANKS_STASH = REGISTRY.register("dark_planks_stash", () -> new DarkPlanksStashBlock());
   public static final RegistryObject<Block> MANGROVE_PLANKS_STASH = REGISTRY.register("mangrove_planks_stash", () -> new MangrovePlanksStashBlock());
   public static final RegistryObject<Block> CHERRY_PLANKS_STASH = REGISTRY.register("cherry_planks_stash", () -> new CherryPlanksStashBlock());
   public static final RegistryObject<Block> WHITE_CONCRETE_BRICKS = REGISTRY.register("white_concrete_bricks", () -> new WhiteConcreteBricksBlock());
   public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_BRICKS = REGISTRY.register(
      "light_gray_concrete_bricks", () -> new LightGrayConcreteBricksBlock()
   );
   public static final RegistryObject<Block> BLACK_CONCRETE_BRICKS = REGISTRY.register("black_concrete_bricks", () -> new BlackConcreteBricksBlock());
   public static final RegistryObject<Block> BROWN_CONCRETE_BRICKS = REGISTRY.register("brown_concrete_bricks", () -> new BrownConcreteBricksBlock());
   public static final RegistryObject<Block> REDCONCRETEBRICKS = REGISTRY.register("redconcretebricks", () -> new RedconcretebricksBlock());
   public static final RegistryObject<Block> ORANGE_CONCRETE_BRICKS = REGISTRY.register("orange_concrete_bricks", () -> new OrangeConcreteBricksBlock());
   public static final RegistryObject<Block> YELLOW_CONCRETE_BRICKS = REGISTRY.register("yellow_concrete_bricks", () -> new YellowConcreteBricksBlock());
   public static final RegistryObject<Block> LIME_CONCRETE_BRICKS = REGISTRY.register("lime_concrete_bricks", () -> new LimeConcreteBricksBlock());
   public static final RegistryObject<Block> GREEN_CONCRETEBRICKS = REGISTRY.register("green_concretebricks", () -> new GreenConcretebricksBlock());
   public static final RegistryObject<Block> CYANCONCRETEBRICKS = REGISTRY.register("cyanconcretebricks", () -> new CyanconcretebricksBlock());
   public static final RegistryObject<Block> LIGHT_BLUECONCRETEBRICKS = REGISTRY.register("light_blueconcretebricks", () -> new LightBlueconcretebricksBlock());
   public static final RegistryObject<Block> BLUE_CONCRETE_BRICKS = REGISTRY.register("blue_concrete_bricks", () -> new BlueConcreteBricksBlock());
   public static final RegistryObject<Block> PURPLE_CONCRETE_BRICKS = REGISTRY.register("purple_concrete_bricks", () -> new PurpleConcreteBricksBlock());
   public static final RegistryObject<Block> MAGENTACONCRETEBRICKS = REGISTRY.register("magentaconcretebricks", () -> new MagentaconcretebricksBlock());
   public static final RegistryObject<Block> PINK_CONCRETE_BRICKS = REGISTRY.register("pink_concrete_bricks", () -> new PinkConcreteBricksBlock());
   public static final RegistryObject<Block> RAIN_COLLECTOR = REGISTRY.register("rain_collector", () -> new RainCollectorBlock());
   public static final RegistryObject<Block> BEARTRAPNEUTRAL = REGISTRY.register("beartrapneutral", () -> new BeartrapneutralBlock());
   public static final RegistryObject<Block> SPRUCE_CRATE = REGISTRY.register("spruce_crate", () -> new SprucecrateBlock());
   public static final RegistryObject<Block> BIRCH_CRATE = REGISTRY.register("birch_crate", () -> new BirchcrateBlock());
   public static final RegistryObject<Block> JUNGLE_CRATE = REGISTRY.register("jungle_crate", () -> new JunglecrateBlock());
   public static final RegistryObject<Block> ACACIA_CRATE = REGISTRY.register("acacia_crate", () -> new AcaciacrateBlock());
   public static final RegistryObject<Block> DARK_CRATE = REGISTRY.register("dark_crate", () -> new DarkcrateBlock());
   public static final RegistryObject<Block> MANGROVE_CRATE = REGISTRY.register("mangrove_crate", () -> new MangrovecrateBlock());
   public static final RegistryObject<Block> CHERRY_CRATE = REGISTRY.register("cherry_crate", () -> new CherrycrateBlock());
   public static final RegistryObject<Block> CORPSECLOTH = REGISTRY.register("corpsecloth", () -> new CorpseclothBlock());
   public static final RegistryObject<Block> CORPSESACK = REGISTRY.register("corpsesack", () -> new CorpsesackBlock());
   public static final RegistryObject<Block> RAIN_COLLECTOR_FULL = REGISTRY.register("rain_collector_full", () -> new RainCollectorFullBlock());
   public static final RegistryObject<Block> VENTCOVER = REGISTRY.register("ventcover", () -> new VentcoverBlock());
   public static final RegistryObject<Block> VENT = REGISTRY.register("vent", () -> new VentBlock());
   public static final RegistryObject<Block> VENT_TURN = REGISTRY.register("vent_turn", () -> new VentturnBlock());
   public static final RegistryObject<Block> VENTBLOCK = REGISTRY.register("ventblock", () -> new VentblockBlock());
   public static final RegistryObject<Block> ROPEEXTENSION = REGISTRY.register("ropeextension", () -> new RopeextensionBlock());
   public static final RegistryObject<Block> CLIMBING_ROPE = REGISTRY.register("climbing_rope", () -> new ClimbingRopeBlock());
   public static final RegistryObject<Block> CLIMBINGROPEEXTENSION = REGISTRY.register("climbingropeextension", () -> new ClimbingropeextensionBlock());
   public static final RegistryObject<Block> CLIMBINGROPEHOOK = REGISTRY.register("climbingropehook", () -> new ClimbingropehookBlock());
   public static final RegistryObject<Block> IRONCRATE = REGISTRY.register("ironcrate", () -> new IroncrateBlock());
   public static final RegistryObject<Block> TRASHBAG = REGISTRY.register("trashbag", () -> new TrashbagBlock());
   public static final RegistryObject<Block> TRASHBAGBLUEPLASTIC = REGISTRY.register("trashbagblueplastic", () -> new TrashbagblueplasticBlock());
   public static final RegistryObject<Block> PAPERTRASH = REGISTRY.register("papertrash", () -> new PapertrashBlock());
   public static final RegistryObject<Block> PAPERSTRASH = REGISTRY.register("paperstrash", () -> new PaperstrashBlock());
   public static final RegistryObject<Block> PAPERTRASHVARIANT = REGISTRY.register("papertrashvariant", () -> new PapertrashvariantBlock());
   public static final RegistryObject<Block> PAPERSTRASHVARIANT_2 = REGISTRY.register("paperstrashvariant_2", () -> new Paperstrashvariant2Block());
   public static final RegistryObject<Block> PAPERSVARIANT_2 = REGISTRY.register("papersvariant_2", () -> new Papersvariant2Block());
   public static final RegistryObject<Block> METELSHELVESFOUR = REGISTRY.register("metelshelvesfour", () -> new MetelshelvesfourBlock());
   public static final RegistryObject<Block> METALSHELVESONE = REGISTRY.register("metalshelvesone", () -> new MetalshelvesoneBlock());
   public static final RegistryObject<Block> METALSHELVESFIVE = REGISTRY.register("metalshelvesfive", () -> new MetalshelvesfiveBlock());
   public static final RegistryObject<Block> TRASH_BIN = REGISTRY.register("trash_bin", () -> new TrashcanBlock());
   public static final RegistryObject<Block> TRASHCANN = REGISTRY.register("trashcann", () -> new TrashcannBlock());
   public static final RegistryObject<Block> TRASHCAN_1 = REGISTRY.register("trashcan_1", () -> new Trashcan1Block());
   public static final RegistryObject<Block> PACK_OF_CANNED_CHILIE = REGISTRY.register("pack_of_canned_chilie", () -> new PackofcannedchilieBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_CORN = REGISTRY.register("pack_of_canned_corn", () -> new PackofcannedcornBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_RABBIT_SOUP = REGISTRY.register(
      "pack_of_canned_rabbit_soup", () -> new PackofcannedrabbitsoupBlock()
   );
   public static final RegistryObject<Block> PACK_OF_CANNED_BEANS = REGISTRY.register("pack_of_canned_beans", () -> new PackofcannedbeansBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_PORK = REGISTRY.register("pack_of_canned_pork", () -> new PackofcannedporkBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_SOUP = REGISTRY.register("pack_of_canned_soup", () -> new PackofcannedsoupBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_FOOD = REGISTRY.register("pack_of_canned_food", () -> new PackofcannedfoodBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_STRAWBERRY = REGISTRY.register("pack_of_canned_strawberry", () -> new PackofcannedstawberryBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_CARROTS = REGISTRY.register("pack_of_canned_carrots", () -> new PackofcannedcarrotsBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_FISH = REGISTRY.register("pack_of_canned_fish", () -> new PackofcannedfishBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_MELON = REGISTRY.register("pack_of_canned_melon", () -> new PackofcannedmelonBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_BEETROOT = REGISTRY.register("pack_of_canned_beetroot", () -> new PackofcannedbeetrootBlock());
   public static final RegistryObject<Block> PACK_OF_CANNED_DOGS_FOOD = REGISTRY.register("pack_of_canned_dogs_food", () -> new PackofcanneddogsfoodBlock());
   public static final RegistryObject<Block> PACK_OF_MILK_BOXES = REGISTRY.register("pack_of_milk_boxes", () -> new PackofmilkboxesBlock());
   public static final RegistryObject<Block> PLANKSD = REGISTRY.register("planksd", () -> new PlanksdBlock());
   public static final RegistryObject<Block> PLANKSE = REGISTRY.register("plankse", () -> new PlankseBlock());
   public static final RegistryObject<Block> PLANK_DOOR = REGISTRY.register("plank_door", () -> new PlankDoorBlock());
   public static final RegistryObject<Block> SPIKEFENCETURN = REGISTRY.register("spikefenceturn", () -> new SpikefenceturnBlock());
   public static final RegistryObject<Block> OAK_LOG_SPIKE = REGISTRY.register("oak_log_spike", () -> new OaklogspikeBlock());
   public static final RegistryObject<Block> SPRUCE_LOG_SPIKE = REGISTRY.register("spruce_log_spike", () -> new SprucelogspikeBlock());
   public static final RegistryObject<Block> BIRCH_LOG_SPIKE = REGISTRY.register("birch_log_spike", () -> new BirchlogspikeBlock());
   public static final RegistryObject<Block> JUNGLE_LOG_SPIKE = REGISTRY.register("jungle_log_spike", () -> new JunglelogspikeBlock());
   public static final RegistryObject<Block> ACACIA_LOG_SPIKE = REGISTRY.register("acacia_log_spike", () -> new AcacialogspikeBlock());
   public static final RegistryObject<Block> MANGROVE_LOG_SPIKE = REGISTRY.register("mangrove_log_spike", () -> new MangrovelogspikeBlock());
   public static final RegistryObject<Block> CHERRY_LOG_SPIKE = REGISTRY.register("cherry_log_spike", () -> new CherrylogspikeBlock());
   public static final RegistryObject<Block> DARK_LOG_SPIKE = REGISTRY.register("dark_log_spike", () -> new DarklogspikeBlock());
   public static final RegistryObject<Block> MECHANICS_TOOL_CHEST = REGISTRY.register("mechanics_tool_chest", () -> new MechanicsToolChestBlock());
   public static final RegistryObject<Block> MILITARY_COMMUNICATION_RADIO = REGISTRY.register(
      "military_communication_radio", () -> new MilitarycommunicationradioBlock()
   );
   public static final RegistryObject<Block> COKE_VENDING_MACHINE = REGISTRY.register("coke_vending_machine", () -> new CokevendingmachineBlock());
   public static final RegistryObject<Block> PORPSI_VENDING_MACHINE = REGISTRY.register("porpsi_vending_machine", () -> new PorpsivendingmachineBlock());
   public static final RegistryObject<Block> MAGAZINE_BOXES = REGISTRY.register("magazine_boxes", () -> new MagazineBoxesBlock());
   public static final RegistryObject<Block> MARKET_SHELVES = REGISTRY.register("market_shelves", () -> new MarketshelvesBlock());
   public static final RegistryObject<Block> MEDICINE_BOXES = REGISTRY.register("medicine_boxes", () -> new MedicineboxesBlock());
   public static final RegistryObject<Block> DROPBOXCOMMON = REGISTRY.register("dropboxcommon", () -> new DropboxcommonBlock());
   public static final RegistryObject<Block> EMPTY_MARKET_SHELVES = REGISTRY.register("empty_market_shelves", () -> new EmptymarketshelvesBlock());
   public static final RegistryObject<Block> LARGE_SHELVES = REGISTRY.register("large_shelves", () -> new LargeshelvesBlock());
   public static final RegistryObject<Block> LARGE_SHELVES_FILL = REGISTRY.register("large_shelves_fill", () -> new LargeshelvesfillBlock());
   public static final RegistryObject<Block> ICE = REGISTRY.register("ice", () -> new IceBlock());
   public static final RegistryObject<Block> WASHING_MACHINE = REGISTRY.register("washing_machine", () -> new WashingmachineBlock());
   public static final RegistryObject<Block> MILITARY_STORAGE = REGISTRY.register("military_storage", () -> new MilitarystorageBlock());
   public static final RegistryObject<Block> DESERT_MILITARY_STORAGE = REGISTRY.register("desert_military_storage", () -> new DesertmilitarystorageBlock());
   public static final RegistryObject<Block> APARTMENT_DOOR = REGISTRY.register("apartment_door", () -> new ApartmentdoorBlock());
   public static final RegistryObject<Block> MEDICALAIRDROPBOX = REGISTRY.register("medicalairdropbox", () -> new MedicalairdropboxBlock());
   public static final RegistryObject<Block> MILITARYAIRDROP = REGISTRY.register("militaryairdrop", () -> new MilitaryairdropBlock());
   public static final RegistryObject<Block> GAS_CANISTER = REGISTRY.register("gas_canister", () -> new GascanisterBlock());
   public static final RegistryObject<Block> LARGE_GAS_CANISTER = REGISTRY.register("large_gas_canister", () -> new LargegascanisterBlock());
   public static final RegistryObject<Block> WHITE_PETROL_BARREL = REGISTRY.register("white_petrol_barrel", () -> new WhitepetrolbarrelBlock());
   public static final RegistryObject<Block> LIGTH_GRAY_PETROL_BARREL = REGISTRY.register("ligth_gray_petrol_barrel", () -> new LigthgraypetrolbarrelBlock());
   public static final RegistryObject<Block> GRAY_PETROL_BARREL = REGISTRY.register("gray_petrol_barrel", () -> new GraypetrolbarrelBlock());
   public static final RegistryObject<Block> BLACK_PETROL_BARREL = REGISTRY.register("black_petrol_barrel", () -> new BlackpetrolbarrelBlock());
   public static final RegistryObject<Block> BROWN_PETROL_BARREL = REGISTRY.register("brown_petrol_barrel", () -> new BrownpetrolbarrelBlock());
   public static final RegistryObject<Block> RED_PETROL_BARREL = REGISTRY.register("red_petrol_barrel", () -> new RedpetrolbarrelBlock());
   public static final RegistryObject<Block> ORANGE_PETROL_BARREL = REGISTRY.register("orange_petrol_barrel", () -> new OrangepetrolbarrelBlock());
   public static final RegistryObject<Block> YELLOW_PETROL_BARREL = REGISTRY.register("yellow_petrol_barrel", () -> new YellowpetrolbarrelBlock());
   public static final RegistryObject<Block> LIME_PETROL_BARREL = REGISTRY.register("lime_petrol_barrel", () -> new LimepetrolbarrelBlock());
   public static final RegistryObject<Block> GREEN_PETROL_BARREL = REGISTRY.register("green_petrol_barrel", () -> new GreenpetrolbarrelBlock());
   public static final RegistryObject<Block> CYAN_PETROL_BARREL = REGISTRY.register("cyan_petrol_barrel", () -> new CyanpetrolbarrelBlock());
   public static final RegistryObject<Block> LIGHT_BLUE_PETROL_BARREL = REGISTRY.register("light_blue_petrol_barrel", () -> new LightbluepetrolbarrelBlock());
   public static final RegistryObject<Block> BLUE_PETROL_BARREL = REGISTRY.register("blue_petrol_barrel", () -> new BluepetrolbarrelBlock());
   public static final RegistryObject<Block> PURPLE_PETROL_BARREL = REGISTRY.register("purple_petrol_barrel", () -> new PurplepetrolbarrelBlock());
   public static final RegistryObject<Block> MAGENTA_PETROL_BARREL = REGISTRY.register("magenta_petrol_barrel", () -> new MagentapetrolbarrelBlock());
   public static final RegistryObject<Block> PINK_PETROL_BARREL = REGISTRY.register("pink_petrol_barrel", () -> new PinkpetrolbarrelBlock());
   public static final RegistryObject<Block> TOXIC_WASTE_BARREL = REGISTRY.register("toxic_waste_barrel", () -> new ToxicwastebarrelBlock());
   public static final RegistryObject<Block> SEWAGE_HATCH = REGISTRY.register("sewage_hatch", () -> new SewageHatchBlock());
   public static final RegistryObject<Block> HIGHVALUEMONEYBLOCK = REGISTRY.register("highvaluemoneyblock", () -> new HighvaluemoneyblockBlock());
   public static final RegistryObject<Block> VENT_ENTRANCE = REGISTRY.register("vent_entrance", () -> new VententranceBlock());
   public static final RegistryObject<Block> MARKETFRIDGE = REGISTRY.register("marketfridge", () -> new MarketfridgeBlock());
   public static final RegistryObject<Block> TALL_BLOCK_PROXY = REGISTRY.register("tall_block_proxy", TallBlockProxyBlock::new);
}
